cargo-features=["edition"]

[package]
edition="2018"
name = "color-science"
version = "0.1.0"
authors = ["Anders Langlands <anderslanglands@gmail.com>"]

[features]
f16 = ["half"]

[dependencies]
num-traits = "0.2"
lazy_static = "1.1"
half = {version="0.1", optional = true}